package com.exchange.exchange;

public class Variables {
    public static String baseURL = "https://www.revolut.com/api/exchange/quote?";
    public static String[][] currencies = {
            {"British Pound", "GBP"},
            {"Euro", "EUR"},
            {"US Dollar", "USD"},
            {"Polish Zloty", "PLN"},
            {"United Arab Emirates Dirham", "AED"},
            {"Afghan Afghani", "AFN"},
            {"Albanian Lek ALL Armenian Dram", "AMD"},
            {"Netherlands Antillean Guilder", "ANG"},
            {"Angolan Kwanza", "AOA"},
            {"Argentine Peso", "ARS"},
            {"Australian Dollar", "AUD"},
            {"Aruban Florin", "AWG"},
            {"Azerbaijani Manat", "AZN"},
            {"Bosnia-Herzegovina Convertible Mark", "BAM"},
            {"Barbadian Dollar", "BBD"},
            {"Bangladeshi Taka", "BDT"},
            {"Bulgarian Lev", "BGN"},
            {"Bahraini Dinar", "BHD"},
            {"BIF", "BIF"},
            {"Bermudan Dollar", "BMD"},
            {"Brunei Dollar", "BND"},
            {"Bolivian Boliviano", "BOB"},
            {"BOV", "BOV"},
            {"Brazilian Real Bahamian Dollar", "BSD"},
            {"BTN", "BTN"},
            {"Botswanan Pula", "BWP"},
            {"Belarusian Ruble", "BYN"},
            {"Belize Dollar", "BZD"},
            {"Canadian Dollar", "CAD"},
            {"CDF", "CDF"},
            {"CHE", "CHE"},
            {"Swiss Franc", "CHF"},
            {"CHW", "CHW"},
            {"CLF", "CLF"},
            {"Chilean Peso", "CLP"},
            {"Chinese Yuan (offshore)", "CNH"},
            {"Chinese Yuan", "CNY"},
            {"Colombian Peso", "COP"},
            {"COU", "COU"},
            {"Costa Rican Colón", "CRC"},
            {"Cuban Convertible Peso", "CUC"},
            {"CUP", "CUP"},
            {"Cape Verdean Escudo", "CVE"},
            {"CYP", "CYP"},
            {"Czech Koruna", "CZK"},
            {"Djiboutian Franc", "DJF"},
            {"Danish Krone", "DKK"},
            {"Dominican Peso", "DOP"},
            {"Algerian Dinar", "DZD"},
            {"Estonian Kroon", "EEK"},
            {"Egyptian Pound", "EGP"},
            {"ERN", "ERN"},
            {"Ethiopian Birr", "ETB"},
            {"EUr", "EUr"},
            {"Fijian Dollar", "FJD"},
            {"Falkland Islands Pound", "FKP"},
            {"Georgian Lari", "GEL"},
            {"GGP", "GGP"},
            {"Ghanaian Cedi", "GHS"},
            {"Gibraltar Pound", "GIP"},
            {"Gambian Dalasi", "GMD"},
            {"Guinean Franc", "GNF"},
            {"Guatemalan Quetzal", "GTQ"},
            {"Guyanaese Dollar", "GYD"},
            {"Hong Kong Dollar", "HKD"},
            {"Honduran Lempira", "HNL"},
            {"Croatian Kuna", "HRK"},
            {"Haitian Gourde", "HTG"},
            {"Hungarian Forint", "HUF"},
            {"Indonesian Rupiah", "IDR"},
            {"Israeli New Shekel", "ILS"},
            {"IMP", "IMP"},
            {"Indian Rupee", "INR"},
            {"Iraqi Dinar", "IQD"},
            {"IRR", "IRR"},
            {"Icelandic Króna", "ISK"},
            {"JEP", "JEP"},
            {"Jamaican Dollar", "JMD"},
            {"Jordanian Dinar", "JOD"},
            {"Japanese Yen", "JPY"},
            {"Kenyan Shilling", "KES"},
            {"Kyrgystani Som", "KGS"},
            {"Cambodian Riel", "KHR"},
            {"KMF", "KMF"},
            {"KPW", "KPW"},
            {"South Korean Won", "KRW"},
            {"Kuwaiti Dinar", "KWD"},
            {"Cayman Islands Dollar", "KYD"},
            {"Kazakhstani Tenge", "KZT"},
            {"Laotian Kip", "LAK"},
            {"Lebanese Pound", "LBP"},
            {"Sri Lankan Rupee", "LKR"},
            {"LRD", "LRD"},
            {"Lesotho Loti", "LSL"},
            {"LTL", "LTL"},
            {"LVL", "LVL"},
            {"LYD", "LYD"},
            {"Moroccan Dirham", "MAD"},
            {"Moldovan Leu", "MDL"},
            {"Malagasy Ariary", "MGA"},
            {"Macedonian Denar", "MKD"},
            {"Myanmar Kyat", "MMK"},
            {"Macanese Pataca", "MOP"},
            {"MRO", "MRO"},
            {"MRU", "MRU"},
            {"Mauritian Rupee", "MUR"},
            {"Maldivian Rufiyaa", "MVR"},
            {"Malawian Kwacha", "MWK"},
            {"Mexican Peso", "MXN"},
            {"MXV", "MXV"},
            {"Malaysian Ringgit", "MYR"},
            {"Mozambican Metical", "MZN"},
            {"Namibian Dollar", "NAD"},
            {"Nigerian Naira", "NGN"},
            {"Nicaraguan Córdoba", "NIO"},
            {"Norwegian Krone", "NOK"},
            {"Nepalese Rupee", "NPR"},
            {"New Zealand Dollar", "NZD"},
            {"Omani Rial", "OMR"},
            {"Panamanian Balboa", "PAB"},
            {"Peruvian Sol", "PEN"},
            {"Papua New Guinean Kina", "PGK"},
            {"Philippine Peso", "PHP"},
            {"Pakistani Rupee", "PKR"},
            {"Paraguayan Guarani", "PYG"},
            {"Qatari Riyal", "QAR"},
            {"Romanian Leu", "RON"},
            {"Serbian Dinar", "RSD"},
            {"Russian Ruble", "RUB"},
            {"Rwandan Franc", "RWF"},
            {"Saudi Riyal", "SAR"},
            {"Solomon Islands Dollar", "SBD"},
            {"Seychellois Rupee", "SCR"},
            {"SDG", "SDG"},
            {"Swedish Krona", "SEK"},
            {"Singapore Dollar", "SGD"},
            {"SHP", "SHP"},
            {"SKK", "SKK"},
            {"Sierra Leonean Leone", "SLE"},
            {"Sierra Leonean Leone (1964—2022)", "SLL"},
            {"SOS", "SOS"},
            {"Surinamese Dollar", "SRD"},
            {"SSP", "SSP"},
            {"STN", "STN"},
            {"Salvadoran Colón", "SVC"},
            {"SYP", "SYP"},
            {"SZL", "SZL"},
            {"Thai Baht", "THB"},
            {"TJS", "TJS"},
            {"TMM", "TMM"},
            {"Turkmenistani Manat", "TMT"},
            {"Tunisian Dinar", "TND"},
            {"Tongan Pa‘anga", "TOP"},
            {"Turkish Lira", "TRY"},
            {"Trinidad & Tobago Dollar", "TTD"},
            {"New Taiwan Dollar", "TWD"},
            {"Tanzanian Shilling", "TZS"},
            {"Ukrainian Hryvnia", "UAH"},
            {"Ugandan Shilling", "UGX"},
            {"USN", "USN"},
            {"UYI", "UYI"},
            {"Uruguayan Peso", "UYU"},
            {"Uzbekistani Som", "UZS"},
            {"VED", "VED"},
            {"Venezuelan Bolívar (2008–2018)", "VEF"},
            {"Venezuelan Bolívar", "VES"},
            {"Vietnamese Dong", "VND"},
            {"Vanuatu Vatu", "VUV"},
            {"WST", "WST"},
            {"Central African CFA Franc", "XAF"},
            {"XBA", "XBA"},
            {"XBB", "XBB"},
            {"XBC", "XBC"},
            {"XBD", "XBD"},
            {"East Caribbean Dollar", "XCD"},
            {"XDR", "XDR"},
            {"XFO", "XFO"},
            {"XFU", "XFU"},
            {"West African CFA Franc", "XOF"},
            {"CFP Franc", "XPF"},
            {"XSU", "XSU"},
            {"XTS", "XTS"},
            {"XUA", "XUA"},
            {"YER", "YER"},
            {"South African Rand", "ZAR"},
            {"ZMK", "ZMK"},
            {"Zambian Kwacha", "ZMW"},
            {"ZWL", "ZWL"}
    };
    private Variables(){}
}
